### ISSUE TITLE
Upgrading to django 1.5

### ISSUE THREAD

**Issue by XaviP** [XaviP/valuenetwork#1]
First approach to update: ([This site](https://nicksergeant.com/upgrading-from-django-1-4-to-django-1-5/) helped a lot) ([Changes in code](https://github.com/FreedomCoop/valuenetwork/compare/master...XaviP:update_django_15))
- Changed *django 1.5* in requeriments.txt
- No problems initializing db
- First errors in tests: *direct_to_template* -> Solved looking for ocurrences with *grep -r 'direct_to_template' ./*
- Second errors in tests: *path to a view function as a string* Solved as described [here](http://stackoverflow.com/questions/14882491/django-release-1-5-url-requires-a-non-empty-first-argument-the-syntax-change#15373978).
- Blocking error:
```
  File "/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 424, in render
    raise e
NoReverseMatch: Reverse for ''home'' with arguments '()' and keyword arguments '{}' not found.
======================================================================
FAIL: test_scheduling (valuenetwork.valueaccounting.tests.test_explosions.ExplosionTest)
dependent demand explosion scheduling:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/tests/test_explosions.py", line 189, in test_scheduling
    self.assertTrue(parent_process.end_date > datetime.date.today())
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by bhaugen** [comment]
I think for this one (and all others in that file) just remove the extra quotation marks. That file had 
{% load url from future %}
which meant it already had quoted named urls.

> NoReverseMatch: Reverse for ''home''

Let me know if that works.

**Comment by bhaugen** [comment]
Lotta changes to those templates. Could you automate it?

**Comment by XaviP** [comment]
Yes, look [here](http://stackoverflow.com/questions/14882491/django-release-1-5-url-requires-a-non-empty-first-argument-the-syntax-change#15373978)

**Comment by bhaugen** [comment]
Nice! 

I have no idea why that test failed. I'll probably need to clone your fork and step thru it in pdb.

**Comment by XaviP** [comment]
Three changes commited:
- Correcting double quotation marks in theme_bootstrap/base.html
- Name of template in valueaccounting/urls.py
- Commenting line 189 in valuenetwork/valueaccounting/tests/test_explosions.py

Now tests pass, and everything seems ok with dev server.
@bhaugen  Do you want me to make a pull request? I think the best way would be creating a new branch in you repo to pull request there.

**Comment by bhaugen** [comment]
> Do you want me to make a pull request? I think the best way would be creating a new branch in you repo to pull request there.

I agree. What do you think about one branch per version upgrade? I also want to check with Lynn about managing branches, she has a lot more experience in that than I do. She should be up in a couple of hours.

**Comment by bhaugen** [comment]
first version branch:
https://github.com/FreedomCoop/valuenetwork/tree/django15

**Comment by bhaugen** [comment]
Ok, the django15 branch up and running and reproduced that test failure. Now to figure out why, since I don't see any changes in the related code in that branch...

**Comment by bhaugen** [comment]
Fixed bug, tests all pass. Was a subtle change in behavior in 1.5 vs 1.4.22. Could research the django change, but figured it out enuf to solve the problem, so I am happy for the moment. Pushed to https://github.com/FreedomCoop/valuenetwork/tree/django15

**Comment by XaviP** [comment]
Great! Thanks @bhaugen !

**Comment by XaviP** [comment]
Closing. Joining to issue to *Upgrading django from 1.4 to 1.6*: 
https://github.com/XaviP/valuenetwork/issues/2
