### ISSUE TITLE
Upgrading django from 1.4 to 1.6

### ISSUE THREAD

**Issue by XaviP** [XaviP/valuenetwork#2]
From django 1.4 to 1.5
================
[This site](https://nicksergeant.com/upgrading-from-django-1-4-to-django-1-5/) helped a lot.
- Changed *django 1.5* in requeriments.txt
- First errors in tests: *direct_to_template* -> Solved looking for ocurrences with *grep -r 'direct_to_template' ./*
- Second errors in tests: *path to a view function as a string* Solved as described [here](http://stackoverflow.com/questions/14882491/django-release-1-5-url-requires-a-non-empty-first-argument-the-syntax-change#15373978). This method for changing templates gets some errors in a file:
    * Correcting double quotation marks in theme_bootstrap/base.html
- Name of template in valueaccounting/urls.py
- Error in line 189 in valuenetwork/valueaccounting/tests/test_explosions.py corrected by @bhaugen 
- USE_TZ in settings.py
- Changed and tested with *django 1.5.12* in requeriments.txt

From django 1.5 to 1.6
================
- Changed *django 1.6* in requeriments.txt
- No more simplejson: *DeprecationWarning: django.utils.simplejson is deprecated; use json instead.*
```
grep -r 'from django.utils import simplejson' ./
grep -rl 'from django.utils import simplejson' ./ | xargs sed -i s@'from django.utils import simplejson'@'import json as simplejson'@g
```
*json* needs a local name (*simplejson*) since in code there's a variable called *json* that conflicts.
- Django 1.6 changed the default value of BooleanField from False to None. It seems that doesn't make problems since we create a new db.
- django.conf.urls.default doesn't exist no more, but ocp seems adapted to this deprecated yet.
- Add in settings.py:
```
TEST_RUNNER = 'django.test.simple.DjangoTestSuiteRunner'
```
This is for django 1.6 to use old kind of tests, but django 1.8 will need the new ones. See:
https://docs.djangoproject.com/es/1.9/releases/1.6/#new-test-runner
- Seems that settings.py file now expected ALLOWED_HOSTS and SECRET_KEY when deploying.
- Changed and tested with django 1.6.11 in requeriments.txt

**Comment by XaviP** [comment]
Preparing the big step to 1.7:
http://andrewsforge.com/article/upgrading-django-to-17/part-3-django-17-new-features/

**Comment by bhaugen** [comment]
This seems pretty serious:
> ImportError: No module named valueaccounting

We put SECRET_KEY in local_settings.py, but maybe settings.py shd have a placeholder.

I think I better clone your stuff and catch up. Will comment more on the 1.5 update issue.

**Comment by XaviP** [comment]
Ok, but the commits uploaded are only for 1.5 django version. The changes of this issue are not commited yet, since I think it's better pull request first the 1.5 upgrade to your repo, and then create another branch here for 1.6.

**Comment by bhaugen** [comment]
Yes, one branch per version will allow us to isolate problems.

**Comment by bhaugen** [comment]
> We put SECRET_KEY in local_settings.py, but maybe settings.py shd have a placeholder.

settings.py already has a placeholder for SECRET_KEY.  Also already has USE_TZ. But not  ALLOWED_HOSTS.

**Comment by XaviP** [comment]
Passing tests in django 1.6 :-) 
See updated first comment.

**Comment by XaviP** [comment]
Closing. Migrating issue to https://github.com/FreedomCoop/valuenetwork/issues/22
